name: indeex
lsi: false
highlighter: pygments
markdown: kramdown
timezone: Asia/Tehran
permalink: /blog/:year/:month/:day/:title
url: https://imisslovelove.github.io/houngking
excerpt_separator: "\n\n"
exclude: [ .DS_Store ]
gems:
  - jekyll-redirect-from
  - jemoji
  - jekyll-mentions
