name: /sBin
lsi: false
pygments: true
markdown: kramdown
timezone: Asia/Tehran
permalink: /blog/:year/:month/:day/:title
exclude: [ nbproject ]
gems:
  - jekyll-redirect-from
  - jemoji
  - jekyll-mentions